feat(dex): add getDexStablisationFee to an api call (WIP)
WavesHQ/wallet-website-api pull request #88
Opened 2023-03-14 11:39 UTC by veralygit

#### What this PR does / why we need it:
as titled

#### Which issue(s) does this PR fixes?:

Fixes #

#### Sample Links & Screenshots:

Link:

<details>
<summary>Desktop Screenshot</summary>

</details>
<details>
<summary>Mobile Screenshot</summary>

</details>

#### Additional comments?:

2023-03-15 06:34 UTC, lykalabrada commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +  const { tokenADisplaySymbol, tokenBDisplaySymbol, network } = req.body;
As discussed offline, we can add a bit of typing for the `req.body` 🙏

2023-03-15 06:37 UTC, kyleleow commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +      tokenADisplaySymbol === "DUSD"
- let's use string equality check and not use `includes()`, to avoid including `xxxDUSDxxx` token
- conditions are hard to read, can we simplify to `tokenADisplaySymbol === "DUSD" || tokenBDisplaySymbol === "DUSD"`

2023-03-15 06:41 UTC, kyleleow commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +  const pairWithFees = poolpairs.filter(
```suggestion
  const pairWithDUSD = poolpairs.filter(
```

2023-03-15 06:44 UTC, veralygit commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +      tokenADisplaySymbol === "DUSD"
when we check pair.displaySymbol we should use .includes as the pair.displaySymbol is eg `DUSD-DFI`

2023-03-15 06:44 UTC, kyleleow commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +      tokenADisplaySymbol === "DUSD"
i think you should first find the the pair that matches the requested tokenA and B display symbol, then check if either of them has `DUSD`.

2023-03-15 06:46 UTC, kyleleow commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +      tokenADisplaySymbol === "DUSD"
i think the api returns the following, so we cant assume tokenA is always `DUSD`
- DUSD-DFI (defined at token A)
- dUSDT-DUSD (defined at token B)
- dUSDC-DUSD (defined at token B)
- dEUROC-DUSD (defined at token B)

2023-03-15 06:48 UTC, kyleleow commented on src/pages/api/v0/wallet/dex-pairs-with-stab-fees.ts
> +  res.json([
instead of hard-coding, can we have a logic to return the pairs if they fulfill these conditions:
- pairs contains `DUSD`
- pairs has `fee`

2023-03-15 06:49 UTC, kyleleow commented on src/pages/api/v0/wallet/dex-pairs-with-stab-fees.ts
> +  res.json([
and then re-use the logic in `dex-stab-fees`

2023-03-15 06:57 UTC, kyleleow commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +      tokenADisplaySymbol === "DUSD"
> or would you prefer if we take the pair.displaySymbol and do a string split to check individually

dont have to split, just do `pair.tokenA.displaySymbol === 'DUSD' || pair.tokenB...`

2023-03-15 07:03 UTC, veralygit commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +      tokenADisplaySymbol === "DUSD"
updated to check if pair token a and token b matches requested token a and token b display symbol 

after that then will check if the pair token a or b is === "DUSD"

2023-03-15 07:30 UTC, kyleleow commented on src/pages/api/v0/wallet/dex-pairs-with-stab-fees.ts
To review the api name to include `best path`

2023-03-15 07:31 UTC, kyleleow commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +      pair.tokenA.displaySymbol === tokenADisplaySymbol &&
sorry OCD kicking in, haha can we interchange line 42 and 43

2023-03-15 09:47 UTC, lykalabrada commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +  const { tokenADisplaySymbol, tokenBDisplaySymbol, network } = req.body;
Let's update to `req.query`. thanks!

2023-03-15 11:04 UTC, kyleleow commented on src/pages/api/v0/wallet/best-path-pairs-with-stab-fees.ts
> +  for (let i = 0; i < pairsWithFees.length; i += 1) {
let's use `forEach()`

2023-03-15 11:07 UTC, kyleleow commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +  const poolpairs = await whaleApiClient.poolpairs.list(200);
add a try-catch since we calling api within an api

2023-03-15 11:07 UTC, kyleleow commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +  const pairWithDUSD = poolpairs.filter(
can we improve this variable naming? so that we can tell from first glance that it is filtered with the param from request

2023-03-15 11:13 UTC, kyleleow commented on src/pages/api/v0/wallet/best-path-pairs-with-stab-fees.ts
> +      (new BigNumber(pair.tokenA.fee?.pct ?? 0).isGreaterThan(0.01) ||
add a comment to provide context on why we have this comparison

2023-03-15 11:15 UTC, kyleleow commented on cypress/e2e/wallet/best-path-pairs-with-stab-fees.spec.ts
> +        { tokenADisplaySymbol: "DUSD", tokenBDisplaySymbol: "dEUROC" },
we'll need to update this test every time we have a new LP pair that has stab fee, anyway we can prevent this?

2023-03-15 11:32 UTC, veralygit commented on cypress/e2e/wallet/best-path-pairs-with-stab-fees.spec.ts
> +        { tokenADisplaySymbol: "DUSD", tokenBDisplaySymbol: "dEUROC" },
should we check typeof item returned instead of deepEqual

2023-03-16 02:11 UTC, kyleleow commented on src/pages/api/v0/wallet/best-path-pairs-with-stab-fees.ts
> +    // check for if the fee is > 0.01 as DEX stabilization fees are more than 0.001 (0.1%)
```suggestion
    // check for if the fee is > 0.001 as DEX stabilization fees are more than 0.001 (0.1%)
```

2023-03-16 02:18 UTC, kyleleow commented on src/pages/api/v0/wallet/best-path-pairs-with-stab-fees.ts
> +    console.log(error);
where would this be logged? i dont think it will be show up in the client side

2023-03-16 02:19 UTC, kyleleow commented on src/pages/api/v0/wallet/best-path-pairs-with-stab-fees.ts
> +    res.json([]);
- when we have an whale api error should we return http 200 with an empty array?

2023-03-16 02:22 UTC, veralygit commented on src/pages/api/v0/wallet/best-path-pairs-with-stab-fees.ts
> +    res.json([]);
if we have whaleapi error should we return the hardcoded path ? 
`[
        { tokenADisplaySymbol: "DUSD", tokenBDisplaySymbol: "DFI" },
        { tokenADisplaySymbol: "DUSD", tokenBDisplaySymbol: "dUSDT" },
        { tokenADisplaySymbol: "DUSD", tokenBDisplaySymbol: "dUSDC" },
        { tokenADisplaySymbol: "DUSD", tokenBDisplaySymbol: "dEUROC" },
      ]`

2023-03-16 02:23 UTC, lykalabrada commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +      fee = "0";
Saw this `fee = "0";` twice, at this point should we just initialize the fee with "0"? We can then just negate this `if` and assign the token fee inside

2023-03-16 03:35 UTC, kyleleow commented on src/pages/api/v0/wallet/best-path-pairs-with-stab-fees.ts
> +    res.json([]);
if whale or ocean is down, i think we should just return 500

2023-03-16 03:39 UTC, kyleleow commented on cypress/e2e/wallet/best-path-pairs-with-stab-fees.spec.ts
> +        { tokenADisplaySymbol: "DUSD", tokenBDisplaySymbol: "dEUROC" },
at first i am thinking should you just check status code like the other `.spec` are doing. But when i thought about it is pretty useless cos it also depending on external factor. The ideal scenario would be able to have a deterministic test that is not dependent on external factor, just like the test in jellyfish we are able to create a local environment, and then we decide what token pairs to be in, and then we call api to that container and assert the pair that we first created.

2023-03-16 10:22 UTC, kyleleow commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +    const poolpairs = await whaleApiClient.poolpairs.list(200);
let's do a recursive call to make sure we retrieve all poolpairs

2023-03-16 10:23 UTC, kyleleow commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +      const tokenfee = filteredTokenPairWithDUSD[0].tokenB.fee
do we need to add check for fee > 0.001?
in relation to this, is it possible to re-use the logic in `best-path-pairs-with-stab-fees.ts`? then we post-process that array by filtering with the request param

2023-03-17 01:53 UTC, kyleleow commented on cypress/e2e/wallet/dex-stab-fees.spec.ts
> +  it("should should 400 error if params are invalid", () => {
test case typo

2023-03-17 02:16 UTC, kyleleow commented on src/pages/api/v0/wallet/poolpairs.utils.ts
> +  return poolpairs;
i said recursive, but actually you can implement it with other ways, e.g.: do-while loop

2023-03-17 02:39 UTC, lykalabrada commented on src/pages/api/v0/wallet/poolpairs.utils.ts
> +  return poolpairs;
Updated! Not a fan of do-while loop so I tried to avoid it, but using it now so that it's also standard with all other recursive functions we have 🙂

2023-03-17 03:03 UTC, kyleleow commented on src/pages/api/v0/wallet/poolpairs.utils.ts
> +  return poolpairs;
i am open to other options haha, what do you have in mind?

2023-03-17 03:13 UTC, lykalabrada commented on src/pages/api/v0/wallet/poolpairs.utils.ts
> +  return poolpairs;
It's fine, let's just use do-while. It's proven and tested haha, standard with other repos as well 🎉

2023-03-17 06:10 UTC, kyleleow commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +  let fee: string | BigNumber = "0";
do we need `BigNumber`?
```suggestion
  let fee: string = "0";
```

2023-03-17 07:02 UTC, pierregee requested changes
Good work dissecting this code 🙏 @veralygit @lykalabrada!

Putting the logic in one place (one endpoint) is more ideal. Less API call for LW, less looping. 
Response should be something like this,
```
'[{
"tokenADisplaySymbol":"DUSD",
"tokenBDisplaySymbol":"DFI", 
dexStabFee: '0.30',
highFeesUrl: 'defiscan.com/DUSD'
}...]
```

Then in LW's code refactor, we can remove this [chunk](https://github.com/DeFiCh/wallet/blob/main/mobile-app/app/screens/AppNavigator/screens/Dex/hook/DexStabilization.ts#L125-L154) and [this](https://github.com/DeFiCh/wallet/blob/main/mobile-app/app/screens/AppNavigator/screens/Dex/hook/DexStabilization.ts#L76-L123)

2023-03-17 07:44 UTC, lykalabrada commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +    );
Thanks for checking! Noted on the things we need to change:
- Only keep one API: `/best-path-pairs-with-stab-fees` list api
- Add both stabilization fees and high fees URL inside `best-path-pairs-with-stab-fees` API
- We have to use `inPct` instead of `pct` (confirmed by Gracia today)

Question: Any suggestion on the API name?

2023-03-17 08:21 UTC, pierregee commented on src/pages/api/v0/wallet/dex-stab-fees.ts
> +    );
pairs-with-stab-info? am actually contemplating with the naming, cos technically there's no bestPath logic in it

2023-03-18 06:56 UTC, pierregee requested changes

2023-03-18 06:56 UTC, pierregee commented on src/pages/api/v0/wallet/pairs-with-stab-info.ts
> +      const highFeesUrl = highFeesUrls[tokenBDisplaySymbol];
```suggestion
      const scanUrl = `https://defiscan.live/dex/${pair.displaySymbol}`
```

2023-03-18 06:56 UTC, pierregee commented on src/pages/api/v0/wallet/pairs-with-stab-info.ts
> +      }
if there's `inPct` in both directions, this part will only be able to return one direction, it probably won't happen anyway as the goal of stab fee is for DUSD -> stableCoin fees. Already discussed this with @lykalabrada that it's fine

Thoughts if we should handle it? @kyleleow @veralygit

2023-03-18 06:56 UTC, pierregee commented on src/pages/api/v0/wallet/poolpairs.utils.ts
> +import {
better to move in utils directory?

2023-03-19 03:22 UTC, veralygit commented on src/pages/api/v0/wallet/pairs-with-stab-info.ts
> +      }
I think is fine since stab fees are DUSD -> stableCoins only

2023-03-20 01:24 UTC, pierregee approved these changes
LGTM!

2023-03-20 02:13 UTC, kyleleow commented on src/utils/poolpairs.ts
> +export const FEE_PCT = 0.001; // (0.1%)
```suggestion
export const MIN_STAB_FEE_PCT = 0.001; // (0.1%)
```

2023-03-20 02:16 UTC, kyleleow commented on src/pages/api/v0/wallet/pairs-with-stab-info.ts
> +      const highFeeScanUrl = `https://defiscan.live/dex/${pair.displaySymbol}`;
not sure what highFeeScanUrl is used for, but since the request accept `network` as param, should we handle the url based on `network` too?

2023-03-20 02:31 UTC, lykalabrada commented on src/pages/api/v0/wallet/pairs-with-stab-info.ts
> +      const highFeeScanUrl = `https://defiscan.live/dex/${pair.displaySymbol}`;
Used for this link: ![image](https://user-images.githubusercontent.com/17063281/226232859-cb302c6f-33f9-4caf-9b05-446098e47fbb.png)

and to remove this piece of code from wallet:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/17063281/226231861-f1935f80-1bab-4a80-a843-5da8bc113f73.png">


hmm yes we can also base it on the network, I'm just not sure if the same `https://defiscan.live/dex/${pair.displaySymbol}` can be applied? since TestNet data is different

For example [TestNet's DFI-dBTC](https://defiscan.live/dex/DFI-dBTC?network=TestNet) doesn't really show the stab fee..

2023-03-20 02:33 UTC, lykalabrada commented on src/pages/api/v0/wallet/pairs-with-stab-info.ts
> +      const highFeeScanUrl = `https://defiscan.live/dex/${pair.displaySymbol}`;
or since we will update the Scan also, maybe this can be handled there too? 💡

2023-03-20 02:34 UTC, kyleleow commented on src/pages/api/v0/wallet/pairs-with-stab-info.ts
> +      const highFeeScanUrl = `https://defiscan.live/dex/${pair.displaySymbol}`;
i think it make sense right? If the poolpair api for a particular network has no stab fee, then we dont have to display the banner

2023-03-20 05:23 UTC, kyleleow commented on src/pages/api/v0/wallet/pairs-with-stab-info.ts
> +      const highFeeScanUrl = `https://defiscan.live/dex/${pair.displaySymbol}`;
i dont think it should handle at the product side @pierregee what's your thought?

2023-03-20 06:07 UTC, lykalabrada commented on src/pages/api/v0/wallet/pairs-with-stab-info.ts
> +      const highFeeScanUrl = `https://defiscan.live/dex/${pair.displaySymbol}`;
Yup makes sense. Updated 🙏

2023-03-20 06:47 UTC, pierregee commented on src/pages/api/v0/wallet/pairs-with-stab-info.ts
> +      const highFeeScanUrl = `https://defiscan.live/dex/${pair.displaySymbol}`;
> i dont think it should handle at the product side @pierregee what's your thought?

Yea, I have no strong opinion on it. As long as LW can link it to scan dex pair, iz all good. Maybe change highFeesUrl to pairDisplaySymbol so the data is not product-centric

2023-03-20 10:28 UTC, merged